# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Rustie Lin
tagline:             UC Berkeley CS, Android, Blockchain
url:                 http://rustielin.github.io
baseurl:             ''
paginate:            20
paginate_path:       "/blog/page:num/"

# About/contact
name:                Rustie Lin
email:               rustielin@berkeley.edu
github:              https://github.com/rustielin

# Custom vars
version:             1.0.0
categorylist:          [distributed systems, blockchain, algorithms, database]
collections:
    notes:
        collections_dir: notes
        output: true
        permalink: /notes/:name


# Plugins
plugins: [jekyll-paginate]

# Github flavored markdown
markdown: kramdown
kramdown:
  auto_ids:      true
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  input:         GFM
  hard_wrap:     false
  footnote_nr:   1
  show_warnings: false
